### ISSUE TITLE
Parent Docker and PHP 7.4 or 8

### ISSUE THREAD

**Issue by rockymontana** [cmer81/docker-ipboard#3]
The parent (registry.cmer.fr/le-monde-des-reptiles/bootstrap/base-app-alpine:latest) doesn't seem to be publicly available?
When I try to pull it I get Service Unavailable and when I try to inspect it I get "Error: No such container".
With IPBoard starting to require php 7.4 I'd like to change base image to use a newer one that supports 7.4 or even 8.

Can you upgrade the base image to support newer PHP or make it available so that I can upgrade it?

**Comment by cmer81** [comment]
Hello @rockymontana 

thank you for your request and I apologize for not answering.
I have released an update that includes PHP 8.1, Let me know if you find any problems.

Regards,
