### ISSUE TITLE
[FEATURE_REQUEST] Support for PHP 8.0.0 or above

### ISSUE THREAD

**Issue by deffcolony** [cmer81/docker-ipboard#4]
@cmer81 
When i try to install the ipboard i get the following error:
**You are running PHP version 7.3.14. You need PHP 7.4.0 or above (8.0.0 or above recommended). You should contact your hosting provider or system administrator to ask for an upgrade.**

Can you make sure the docker hub image supports PHP 8.0.0 or above? (8.1 is the latest version)

**Comment by cmer81** [comment]
Hello @deffcolony 

thank you for your request and I apologize for not answering.
I have released an update that includes PHP 8.1, Let me know if you find any problems.

Regards,
